packages:
  - 'packages/*'
  - 'examples/*'
  - 'packages/eslint-plugin/test-app'
allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: false
  sharp: false
patchedDependencies:
  '@astrojs/starlight@0.39.2': patches/@astrojs__starlight@0.39.2.patch
