packages:
  - 'packages/*'
  - 'examples/*'
  - 'packages/eslint-plugin/test-app'
  - 'packages/cli/examples/*'
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: false
patchedDependencies:
  '@astrojs/starlight@0.39.2': patches/@astrojs__starlight@0.39.2.patch
