packages:
  - 'packages/*'
  - 'examples/*'
  - 'packages/eslint-plugin/test-app'
allowBuilds:
  esbuild: false
  sharp: false
patchedDependencies:
  '@astrojs/starlight@0.39.2': patches/@astrojs__starlight@0.39.2.patch
